"""
HezCast Engine — Nginx Configuration Generator
Gap 3: Subdomain Routing + Security Headers + Admin IP Restriction
Tinlance Limited | Apache 2.0

Generates production-grade Nginx config for:
  hezcast.com          → Vercel (landing page)
  app.hezcast.com      → Vercel (SaaS dashboard)
  api.hezcast.com      → FastAPI on port 8503
  admin.hezcast.com    → FastAPI admin (IP-restricted)
  www.hezcast.com      → redirect to hezcast.com

Security:
  - IP restriction on admin subdomain
  - HSTS + security headers on all routes
  - server_tokens off (no version leak)
  - TLS 1.2/1.3 only
  - CORS headers on API subdomain

Usage:
  from deploy.nginx_generator import NginxConfigGenerator

  gen = NginxConfigGenerator()
  config = gen.generate({
      "domain":    "hezcast.com",
      "api_port":  8503,
      "app_url":   "https://hezcast-saas.vercel.app",
      "admin_ip":  "YOUR_IP",
      "email":     "your@email.com",
  })
  gen.save_config(config_dict, "/etc/nginx/sites-available/hezcast.com")
"""

import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


class NginxConfigGenerator:
    """
    Generates production-grade Nginx configuration for HezCast.

    Usage:
        gen    = NginxConfigGenerator()
        config = gen.generate(config_dict)
        gen.save_config(config_dict, "/etc/nginx/sites-available/hezcast.com")
    """

    def generate(self, config: dict) -> str:
        """
        Generate complete Nginx configuration string.

        Args:
            config: dict with domain, api_port, app_url, admin_ip, email

        Returns:
            Full Nginx config as string
        """
        domain   = config["domain"]
        api_port = config.get("api_port", 8503)
        app_url  = config.get("app_url", f"https://app.{domain}")
        admin_ip = config.get("admin_ip", "127.0.0.1")
        email    = config.get("email", f"admin@{domain}")

        return f"""# ══════════════════════════════════════════════════════════════
# HezCast — Nginx Configuration
# Generated by deploy/nginx_generator.py
# Domain: {domain}
# ══════════════════════════════════════════════════════════════

# Global security settings
server_tokens off;

# ── HTTP → HTTPS redirect (all subdomains) ─────────────────
server {{
    listen 80;
    listen [::]:80;
    server_name {domain} www.{domain} api.{domain} app.{domain} admin.{domain};

    # Certbot ACME challenge
    location /.well-known/acme-challenge/ {{
        root /var/www/certbot;
    }}

    # Redirect all HTTP to HTTPS
    location / {{
        return 301 https://$host$request_uri;
    }}
}}

# ── www → apex redirect ─────────────────────────────────────
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name www.{domain};

    ssl_certificate     /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://{domain}$request_uri;
}}

# ── Landing page: {domain} ──────────────────────────────────
# Serves static files or proxies to Vercel
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name {domain};

    ssl_certificate     /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    # TLS hardening
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    # Proxy to Vercel (or serve static files)
    location / {{
        proxy_pass         https://hezcast-saas.vercel.app;
        proxy_set_header   Host hezcast-saas.vercel.app;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_ssl_server_name on;
    }}
}}

# ── SaaS Dashboard: app.{domain} ────────────────────────────
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name app.{domain};

    ssl_certificate     /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location / {{
        proxy_pass         {app_url};
        proxy_set_header   Host hezcast-saas.vercel.app;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_ssl_server_name on;
    }}
}}

# ── FastAPI Backend: api.{domain} ───────────────────────────
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name api.{domain};

    ssl_certificate     /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;

    # CORS headers for API consumers
    add_header Access-Control-Allow-Origin "$http_origin" always;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-API-Key" always;
    add_header Access-Control-Allow-Credentials "true" always;

    # Handle CORS preflight
    if ($request_method = OPTIONS) {{
        return 204;
    }}

    # Rate limiting (protect from abuse)
    limit_req_zone $binary_remote_addr zone=api:10m rate=30r/m;
    limit_req zone=api burst=10 nodelay;

    # Proxy to FastAPI
    location / {{
        proxy_pass         http://127.0.0.1:{api_port};
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
        proxy_send_timeout 300;
        client_max_body_size 100M;
    }}

    # Health check — no rate limit
    location /health {{
        proxy_pass       http://127.0.0.1:{api_port}/health;
        proxy_set_header Host $host;
        limit_req_status 429;
    }}
}}

# ── Admin Panel: admin.{domain} (IP-RESTRICTED) ─────────────
# ⚠️  ONLY accessible from your IP address
# Never expose this to the public internet
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name admin.{domain};

    ssl_certificate     /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # ⚠️  IP RESTRICTION — CRITICAL SECURITY CONTROL
    # Only your IP can access admin
    allow {admin_ip};
    deny  all;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Cache-Control "no-store, no-cache, must-revalidate" always;

    # Do not index admin in search engines
    add_header X-Robots-Tag "noindex, nofollow" always;

    location / {{
        proxy_pass         http://127.0.0.1:{api_port};
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Admin-Request "true";
        proxy_read_timeout 300;
    }}
}}

# ── Docs: docs.{domain} ─────────────────────────────────────
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name docs.{domain};

    ssl_certificate     /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;

    location / {{
        proxy_pass         https://hezcast-saas.vercel.app/docs;
        proxy_set_header   Host hezcast-saas.vercel.app;
        proxy_ssl_server_name on;
    }}
}}
"""

    def save_config(self, config: dict, output_path: str) -> str:
        """
        Generate and save Nginx config to file.

        Args:
            config:      Config dict (same as generate())
            output_path: File path to write config

        Returns:
            output_path (str)
        """
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        content = self.generate(config)
        Path(output_path).write_text(content, encoding="utf-8")
        logger.info(f"Nginx config saved: {output_path}")
        return output_path
